### ISSUE TITLE
KeyError: 'Contract Contents'

### ISSUE THREAD

**Issue by LiquidFlame** [makeasnek/FindTheMag#6]
I am getting the following error when running `python main.py`

Traceback (most recent call last):
  File "C:\Users\LiquidFlame\Desktop\FindTheMag\main.py", line 708, in <module>
    mag_ratios = get_project_mag_ratios(grc_client)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LiquidFlame\Desktop\FindTheMag\main.py", line 498, in get_project_mag_ratios
    for project_name, project_stats in superblock['result'][0]['Contract Contents']['projects'].items():
                                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Contract Contents'

C:\Users\LiquidFlame\Desktop\FindTheMag>

**Comment by makeasnek** [comment]
Can you set error log to debug in your user_config.py and send the debug.log to makeasnek {at} gmail.com? Make sure you are on the latest version of FindTheMag and Gridcoin wallet

**Comment by GameDevKitY** [comment]
same issue here

**Comment by makeasnek** [comment]
@GameDevKitY Thank you for the bug report! Can you set error log to debug in your user_config.py and send the debug.log to makeasnek {at} gmail.com? Make sure you are on the latest version of FindTheMag and Gridcoin wallet

**Comment by makeasnek** [comment]
Actually, I just realized this issue is on the old FTM repo. Download the newest FTM here:
https://github.com/makeasnek/FindTheMag2
